### ISSUE TITLE
Navigation issues

### ISSUE THREAD

**Issue by Stanzilla** [ultrabug/mkdocs-static-i18n#12] opened 2021-03-16 11:39 UTC
So I used the following conf:

```yaml
  - i18n:
      default_language: en
      languages:
        fr: français
```

and as expected my EN/default site works the same way as before but switching to French via the language picker dropdown switches the content to the french page. 

Now here's the problem, as soon as I'm on the french version of my index, the menu no longer shows. 

I'm assuming it is because of the autolinks plugin because I also get a lot of these:

```
WARNING -  A relative path to 'getting_started/installing_core.md' is included in the 'nav' configuration, which is not found in the documentation files 
WARNING -  A relative path to 'getting_started/editor_intro.md' is included in the 'nav' configuration, which is not found in the documentation files 
WARNING -  A relative path to 'getting_started/my_first_multiplayer_game.md' is included in the 'nav' configuration, which is not found in the documentation files 
WARNING -  A relative path to 'getting_started/publishing.md' is included in the 'nav' configuration, which is not found in the documentation files 
WARNING -  A relative path to 'getting_started/core_help.md' is included in the 'nav' configuration, which is not found in the documentation files 
WARNING -  A relative path to 'getting_started/community_content.md' is included in the 'nav' configuration, which is not found in the documentation files 
WARNING -  A relative path to 'getting_started/performance_panel.md' is included in the 'nav' configuration, which is not found in the documentation files 
WARNING -  A relative path to 'getting_started/profiler.md' is included in the 'nav' configuration, which is not found in the documentation files 
WARNING -  A relative path to 'getting_started/publishing_checklist.md' is included in the 'nav' configuration, which is not found in the documentation files 
```

When trying to access any other page, it also fails to load them, example:

On `getting_started/installing_core/` manually changing the path in the address bar to `fr/getting_started/installing_core/` should show a page, yet does not?

Here's my branch where I am testing this: https://github.com/ManticoreGamesInc/platform-documentation/tree/localization

**Comment by ultrabug** [comment] 2021-04-06 13:19
Sorry @Stanzilla I was fixing another issue on #13 and did not pay attention to your issue.

I'll check it out and answer ASAP now that version 0.6 is out

**Comment by ultrabug** [comment] 2021-04-06 13:30
While we're at it, could you check if by any chance the fixes I made on 0.6 are helping for your problem?

I don't know the autolinks plugin. The best to help me debug your problem would be the result of a (trimmed) `tree` of your `site` build and expectation.

The output structures are actually tested on this project so maybe there's a case that my tests did not catch?

**Comment by Stanzilla** [comment] 2021-04-06 13:53
> The Autolinks plugins allows you to link to pages and images within your MkDocs site without provided the entire relative path to the file in your document structure.

https://github.com/midnightprioriem/mkdocs-autolinks-plugin

And I tried 0.6.0, it does show the same results and my layout looks like this:

![image](https://user-images.githubusercontent.com/75278/113721277-ac7aa100-96ef-11eb-9ed3-9f781d033329.png)


which does look correct but the menu in the resulting /fr/ page is wrong since it does not generate the french pages and links to them, example:

![image](https://user-images.githubusercontent.com/75278/113721905-3591d800-96f0-11eb-8f58-937d3514cdd0.png)


There are french versions of the markdown files in /getting_started/ but they are not in the site/fr/getting_started output

**Comment by ultrabug** [comment] 2021-04-06 13:54
What I can see so far is that if I remove all other plugins and modify your `mkdocs.yml` like this:

```
plugins:
  - i18n:
      default_language: en
      languages:
        fr: français
```

Then build your documentation, I get the correct file structure:

```
$ tree site/getting_started
site/getting_started
├── community_content
│   └── index.html
├── core_help
│   └── index.html
├── editor_intro
│   └── index.html
├── installing_core
│   └── index.html
├── my_first_multiplayer_game
│   └── index.html
├── performance_panel
│   └── index.html
├── profiler
│   └── index.html
├── publishing
│   └── index.html
└── publishing_checklist
    └── index.html


$ tree site/fr/getting_started
site/fr/getting_started
├── community_content
│   └── index.html
├── core_help
│   └── index.html
├── editor_intro
│   └── index.html
├── installing_core
│   └── index.html
├── my_first_multiplayer_game
│   └── index.html
├── performance_panel
│   └── index.html
├── profiler
│   └── index.html
├── publishing
│   └── index.html
└── publishing_checklist
    └── index.html
```

So there is a plugin that injects / manipulates pages into the navigation and that is ran after the i18n plugin runs and that makes the output different.

**Comment by ultrabug** [comment] 2021-04-06 13:58
It looks like the `redirects` plugin is the culprit and messes up with the i18n navigation.

Can you first confirm that if you remove it, you get the correct output structure?

**Comment by ultrabug** [comment] 2021-04-06 13:59
> There are french versions of the markdown files in /getting_started/ but they are not in the site/fr/getting_started output

You mean you don't get what I do in https://github.com/ultrabug/mkdocs-static-i18n/issues/12#issuecomment-814139787 ?

**Comment by Stanzilla** [comment] 2021-04-06 14:05
> > There are french versions of the markdown files in /getting_started/ but they are not in the site/fr/getting_started output
> 
> You mean you don't get the same output as I do in [#12 (comment)](https://github.com/ultrabug/mkdocs-static-i18n/issues/12#issuecomment-814139787) ?

Disregard that, I was looking at old data.



> It looks like the `redirects` plugin is the culprit and messes up with the i18n navigation.
> 
> Can you first confirm that if you remove it, you get the correct output structure?

I removed `redirects` but I'm not seeing a menu without it either.

**Comment by ultrabug** [comment] 2021-04-06 14:18
Ok I tried generating the translated structure again and it looks to me to be working as expected.

If I `diff` the base url index.html and the translated resulting index.html I see that the one in the `fr` version is indeed in French, don't you?

```
$ diff -u site/getting_started/community_content/index.html site/fr/getting_started/community_content/index.html

...

-        <title>Community Content - Core Documentation</title>
+        <title>Contenu de la communauté - Core Documentation</title>

...
```

Maybe I'm not looking at the right thing?

**Comment by Stanzilla** [comment] 2021-04-06 14:27
Okay here is a deploy preview https://deploy-preview-536--manticore-docs.netlify.app/

Maybe I understood something wrong? What I do is go to the language selector on the site and it switches to the index page in french correctly but then has no menu on the left side.

**Comment by ultrabug** [comment] 2021-04-06 19:34
There's something in your build process that generates an anchor to `#about-the-documentation` which gets translated to french and breaks the navigation but I've been unable to understand where so far...

**Comment by Stanzilla** [comment] 2021-04-06 20:12
Could it be the TOC?

**Comment by ultrabug** [comment] 2021-04-06 23:25
Nah, found that it's caused by `navigation.tracking`.. but it's not the culprit... (tbh I find this option behavior weird because I have a 4K screen so when I get to the home page it "guesses" that I've read everything on the page and forces the anchor to be the last item of the TOC...)

**Comment by Stanzilla** [comment] 2021-04-06 23:28
that sounds like a bug though

**Comment by ultrabug** [comment] 2021-04-07 05:08
I'm closing in @Stanzilla I can now confirm that we have a bug here too ;)

The problem comes from the fact that your navigation is static and thus pointing to non translated md files which are not present in the language specific copies of the site:

Quick example (ugly) fix:
```
nav:
  - Documentation:
      - Home: index.md
      - Home: index.fr.md
```

**Comment by ultrabug** [comment] 2021-04-07 10:35
I think I nailed it @Stanzilla, would it be possible for you to test using https://github.com/ultrabug/mkdocs-static-i18n/pull/18 please?

If that works, I'll add tests and make a new release for you :)

**Comment by Stanzilla** [comment] 2021-04-07 18:00
Pushed the change to https://localization--manticore-docs.netlify.app/ and it does indeed look like its working? Wohoo, thank you!

**Comment by ultrabug** [comment] 2021-04-07 19:19
That looks wonderful, adding tests now then :)

**Comment by Stanzilla** [comment] 2021-04-07 20:04
@ultrabug should I make a follow up issue about more compat with `autolinks` then? It still complains about a lot of relative path problems

**Comment by Stanzilla** [comment] 2021-04-07 20:42
oh and I also noticed that it does not seem to work on a local server with `mkdocs serve` while it is fine with build

**Closed** 2021-04-07 21:44 UTC

**Comment by ultrabug** [comment] 2021-04-07 21:47
version 0.7 is out mate

**Comment by Stanzilla** [comment] 2021-04-07 21:56
Thank you, updating my branch! 

> yep? it works for me :/

Does it work with my repo or a local test?
