### ISSUE TITLE
Localized names for theme switch

### ISSUE THREAD

**Issue by JokelBaf** [ultrabug/mkdocs-static-i18n#239] opened 2023-08-23 13:10 UTC
Hello! I was wondering if there is any way to localize these switch names for dark and light themes:

```yml
theme:
  ...
  palette:
    - scheme: default
      toggle:
        icon: fontawesome/solid/moon
        name: Switch to dark mode
    - scheme: slate 
      toggle:
        icon: fontawesome/solid/sun
        name: Switch to light mode    
```

What I tried was:
```yml
plugins:
  - i18n:
      docs_structure: folder
      languages:
        - locale: en
          name: English
          build: true
          default: true
          theme:
            palette:
              - scheme: default
                toggle:
                  name: Switch to dark mode
              - scheme: slate 
                toggle:
                  name: Switch to light mode
        - locale: ru 
          name: Русский
          build: true
          theme:
            palette:
              - scheme: default
                toggle:
                  name: Включить тёмную тему
              - scheme: slate 
                toggle:
                  name: Включить светлую тему
```
But I got the following error:
```
Traceback (most recent call last):
  File "C:\Users\me\AppData\Local\Programs\Python\Python311\Lib\site-packages\mkdocs\livereload\__init__.py", line 190, in _build_loop
    func()
  File "C:\Users\me\AppData\Local\Programs\Python\Python311\Lib\site-packages\mkdocs\commands\serve.py", line 67, in builder
    build(config, live_server=None if is_clean else server, dirty=is_dirty)
  File "C:\Users\me\AppData\Local\Programs\Python\Python311\Lib\site-packages\mkdocs\commands\build.py", line 340, in build
    _build_theme_template(template, env, files, config, nav)
  File "C:\Users\me\AppData\Local\Programs\Python\Python311\Lib\site-packages\mkdocs\commands\build.py", line 110, in _build_theme_template
    output = _build_template(template_name, template, files, config, nav)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\me\AppData\Local\Programs\Python\Python311\Lib\site-packages\mkdocs\commands\build.py", line 89, in _build_template
    output = template.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\me\AppData\Local\Programs\Python\Python311\Lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\Users\me\AppData\Local\Programs\Python\Python311\Lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\me\AppData\Local\Programs\Python\Python311\Lib\site-packages\material\404.html", line 4, in top-level template code
    {% extends "main.html" %}
  File "C:\Users\me\AppData\Local\Programs\Python\Python311\Lib\site-packages\material\main.html", line 4, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\me\AppData\Local\Programs\Python\Python311\Lib\site-packages\material\base.html", line 143, in top-level template code
    {% block header %}
  File "C:\Users\me\AppData\Local\Programs\Python\Python311\Lib\site-packages\material\base.html", line 144, in block 'header'
    {% include "partials/header.html" %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\me\AppData\Local\Programs\Python\Python311\Lib\site-packages\material\partials\header.html", line 47, in top-level template code
    {% include ".icons/" ~ option.toggle.icon ~ ".svg" %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\me\AppData\Local\Programs\Python\Python311\Lib\site-packages\jinja2\loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: .icons/.svg
```

Am I doing something wrong? I have no idea what this error means because I have never saw it before and it is gone when I remove `theme` from locales in mkdocs.yml. I am using mkdocs-static-i18n `1.0.0`.

**Comment by ultrabug** [comment] 2023-08-23 13:31
@JokelBaf I'm impressed by how fast you gave a try to the upcoming release :tornado: !

Can you provide me with a repository I can reproduce this from maybe?

**Comment by ultrabug** [comment] 2023-08-23 14:50
@JokelBaf thanks. This happens because the theme override for languages does not specify the `icon` option which is not copied over by the plugin. That's a bug on my part, working on a fix!

**Comment by ultrabug** [comment] 2023-08-23 15:16
Fixed on main branch ;) thanks again

**Closed** 2023-08-23 15:16 UTC

**Comment by ultrabug** [comment] 2023-08-24 07:31
> Is there any way to localize site_description? When I tried to use site_description property in the plugin config, I got a "Unrecognised configuration name" warning.

I just tried and it works as intended, maybe you misspelled it? please show a YAML

**Comment by ultrabug** [comment] 2023-08-24 15:13
My eyes were not seeing those mkdocs generated WARNING messages :see_no_evil: sorry!

I know how to fix that, gimme a few

**Comment by ultrabug** [comment] 2023-08-24 15:37
done, warnings should be gone!
