### ISSUE TITLE
[Bug] html `lang` attribute not changing on language switch

### ISSUE THREAD

**Issue by Stanzilla** [ultrabug/mkdocs-static-i18n#39] opened 2021-06-14 14:23 UTC
Example page: https://docs.coregames.com/

Steps: 
- Go to above website, inspect and check HTML's `lang` tag value. It should be `en`.
- Use the language switcher and switch to Francais (Beta). `lang` stays at `en`.

Config: 

```yml
  - i18n:
      default_language: en
      languages:
        fr: Français (Beta)
```

It works on https://ultrabug.github.io/mkdocs-static-i18n/ so I'm suspecting some config.

**Comment by ultrabug** [comment] 2021-06-14 16:39
```
site/fr/tutorials/lua_basics_manticoin/index.html:<html lang="fr" class="no-js">
site/fr/tutorials/lua_basics_manticoin/index.html:                  <a href="/fr/" hreflang="fr" class="md-select__link">
site/fr/index.html:<html lang="fr" class="no-js">
site/fr/index.html:                  <a href="/fr/" hreflang="fr" class="md-select__link">
```

I can't reproduce on your `development` branch

**Comment by Stanzilla** [comment] 2021-06-14 17:02
@ultrabug Uh, really? With the current state?

**Comment by ultrabug** [comment] 2021-06-14 17:21
yep, latest development commit

**Comment by Stanzilla** [comment] 2021-06-14 17:23
> yep, latest development commit ab913dfed544265d4f4e44d2dc9b6d1974a8c19d

oh that is not latest but that at least gives me a place to start bisecting. 

https://github.com/ManticoreGamesInc/platform-documentation/compare/ab913dfed544265d4f4e44d2dc9b6d1974a8c19d..development

Latest is https://github.com/ManticoreGamesInc/platform-documentation/commit/0e27cfaa45972176c3815f9e970cf75b2b0c3793

**Comment by Stanzilla** [comment] 2021-06-14 17:34
Now I'm extra confused because I can't repro it on that commit either.. Hrm.

**Comment by Stanzilla** [comment] 2021-06-15 19:44
@ultrabug any hints on where I could start looking?

**Comment by ultrabug** [comment] 2021-06-15 19:56
> Now I'm extra confused because I can't get it to work on that commit either.. Hrm.

You mean you can reproduce? did you recreate your venv? tbh I don't really know where to start because I was under the impression that I was doing the right thing and that it works as intended on the demo website...

**Comment by Stanzilla** [comment] 2021-06-15 19:59
Since it does not work in my env and not on Netlify either, I assume it's something else. What I meant is that I can not get it to work on the commit you tried or on the latest.

**Comment by Stanzilla** [comment] 2021-06-16 16:21
Yeah does not work with a fresh venv either...I don't get it at all. Tried with default material theme, tried with i18n as the only plugin..

**Comment by Stanzilla** [comment] 2021-06-16 20:04
@ultrabug Can you try on the latest commit again please? I tested on 3 systems now and it does not work anywhere :(

**Comment by ultrabug** [comment] 2021-06-18 16:30
ok I'll give it a try again

```
* commit b1ae0eddd2cb04091b2d0259646e93aa32a77152 (HEAD -> development, origin/development, origin/HEAD)
| Author: Apalatn <apalatn@gmail.com>
| Date:   Tue Jun 15 09:55:54 2021 -0700
```

brand new venv, with requirements.txt installed

running with `DEFAULT_LANGUAGE_ONLY=false mkdocs serve`

**Comment by Stanzilla** [comment] 2021-06-18 17:39
> ok I'll give it a try again
> 
> ```
> * commit b1ae0eddd2cb04091b2d0259646e93aa32a77152 (HEAD -> development, origin/development, origin/HEAD)
> | Author: Apalatn <apalatn@gmail.com>
> | Date:   Tue Jun 15 09:55:54 2021 -0700
> ```
> 
> brand new venv, with requirements.txt installed
> 
> running with `DEFAULT_LANGUAGE_ONLY=false mkdocs serve`

And it works?

**Comment by ultrabug** [comment] 2021-06-18 17:56
> And it works?

No... I can reproduce the problem now, I'll have a look

**Comment by Stanzilla** [comment] 2021-06-18 18:00
> > And it works?
> 
> No... I can reproduce the problem now, I'll have a look

Oh my god, that makes me so happy, haha. I was going crazy here.

**Comment by ultrabug** [comment] 2021-06-18 18:08
Ok I found why, this is because your `theme.name` is `null` and you derive material from a git submodule

This means that mkdocs-static-i18n cannot detect the material theme and thus does not set the theme.language for you (and you explicitly force the theme.language to be `en`)

**Comment by Stanzilla** [comment] 2021-06-18 18:10
Oh that makes sense. I had actually tried not setting `theme.language` but that causes material to fail compiling as well...

**Comment by ultrabug** [comment] 2021-06-18 18:24
It does because you use it through a custom_dir and the material code can't find the language file since it's not a proper material distribution. In a sense, it suffers from the same problem as mkdocs-static-i18n.

If you use theme.name: material you can omit the language parameter just fine!

I suggest you just pin your material version and use overrides where appropriate mate.

As it is, this is not a mkdocs-static-i18n bug to me.

**Comment by Stanzilla** [comment] 2021-06-18 18:27
@ultrabug problem with that is that it is a very very customized fork that not only uses overrides...

**Comment by ultrabug** [comment] 2021-06-18 18:30
I understand mate.

Maybe there's another way to get the name of the theme that's being used instead of just reading the one declared from the config file when it's set to null

I'll give it a try and try to be smart, stay tuned (after dinner) :)

**Comment by Stanzilla** [comment] 2021-06-18 19:50
@ultrabug awesome, thank you. how about the `generator` meta tag?

**Comment by ultrabug** [comment] 2021-06-18 19:51
@Stanzilla dumb question but...

```
theme:
  name: material
  custom_dir: mkdocs-material/material
```

isn't that supposed to work? quick look at mkdocs code and it looks like it should....

**Comment by ultrabug** [comment] 2021-06-18 20:01
> @ultrabug awesome, thank you. how about the generator meta tag?

I'd rather not start parsing HTML nope

But I believe that you actually don't need to set theme.name to null and still benefit from your customization

**Comment by Stanzilla** [comment] 2021-06-18 20:16
yep. you are are totally right and that fixed it! Thank you so much!

**Comment by ultrabug** [comment] 2021-06-18 20:16
ahah, best fix is no fix ;) enjoy mate, closing

**Closed by ultrabug** 2021-06-18 20:16 UTC
